# -*- coding: utf-8 -*-
"""automate_nyoman-arini-trirahayu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RsvCTwjN9e8ZJe6Hwcf2sRPrXl1s1Dat
"""

import pandas as pd
from sklearn.preprocessing import LabelEncoder, StandardScaler
import os

import pandas as pd
import os
from sklearn.preprocessing import LabelEncoder


DATA_PATH = "https://docs.google.com/spreadsheets/d/e/2PACX-1vSzhHCHLSCqZ1wFUBxUo4FsGbuvKuvxSiNo6vFxqy3v-3e6Fh51nk9pWU87-BxOv2VxhFD1U1aLI2SU/pub?gid=826766192&single=true&output=csv"
OUTPUT_DIR = "preprocessing"
OUTPUT_FILENAME = "churn_preprocessed.csv"


def preprocess_data(data_path: str) -> pd.DataFrame:
    """
    Melakukan preprocessing data Customer Churn secara otomatis
    berdasarkan hasil eksperimen pada notebook.
    """
    try:
        df = pd.read_csv(data_path)
    except Exception as e:
        print(f"Gagal memuat dataset: {e}")
        return pd.DataFrame()

    print("1. Dataset berhasil dimuat.")

    # Drop kolom identifier
    drop_cols = ['RowNumber', 'CustomerId', 'Surname']
    df = df.drop(columns=[col for col in drop_cols if col in df.columns])
    print("2. Kolom identifier berhasil dihapus.")

    # Encoding fitur kategorikal
    categorical_cols = df.select_dtypes(include=['object']).columns
    le = LabelEncoder()

    for col in categorical_cols:
        df[col] = le.fit_transform(df[col])

    print("3. Encoding fitur kategorikal berhasil.")

    return df


if __name__ == "__main__":

    os.makedirs(OUTPUT_DIR, exist_ok=True)

    print("Memulai proses preprocessing otomatis...")
    processed_df = preprocess_data(DATA_PATH)

    if not processed_df.empty:
        output_path = os.path.join(OUTPUT_DIR, OUTPUT_FILENAME)
        processed_df.to_csv(output_path, index=False)
        print(f"\nPreprocessing selesai. Dataset tersimpan di: {output_path}")
        print("Shape dataset:", processed_df.shape)

import pandas as pd
df = pd.read_csv("./preprocessing/churn_preprocessed.csv")
df.head()