# -*- coding: utf-8 -*-
"""Eksperimen MSML Nyoman Aini Trirahayu

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16y20AhjiPfNwG8thA4VfG82Ep3cjISuA

# **1. Perkenalan Dataset**

# Pengenalan Dataset: Bank Customer Churn

Dataset yang digunakan berasal dari **Bank Customer Churn Dataset**, yaitu kumpulan data pelanggan bank yang bertujuan untuk memprediksi apakah seorang pelanggan akan berhenti menggunakan layanan bank (churn) atau tetap aktif. Dataset ini sering digunakan untuk **analisis retensi pelanggan**, **machine learning supervised classification**, serta **eksperimen MLOps** karena memiliki kombinasi fitur numerik dan kategorikal yang seimbang.  

Dataset ini bersifat publik dan banyak digunakan untuk keperluan edukasi dan eksperimen prediksi churn. Dataset mencerminkan perilaku nyata pelanggan bank, walaupun data ini disediakan dalam bentuk fiktif.

### 🎯 Tujuan Penggunaan Dataset
- Menganalisis karakteristik pelanggan bank.  
- Memahami faktor-faktor yang mempengaruhi churn.  
- Mengembangkan model prediksi churn menggunakan machine learning.

### 🧮 Jumlah Data
- **Baris (Rows):** 10.000 pelanggan (contoh; sesuaikan jika berbeda)  
- **Kolom (Features):** 14 fitur + 1 target (Churn)

### 🧩 Deskripsi Kolom

| Fitur | Tipe | Deskripsi |
|-------|------|-----------|
| RowNumber | int | Nomor baris pelanggan |
| CustomerId | object | ID unik pelanggan |
| Surname | object | Nama belakang pelanggan |
| CreditScore | int | Skor kredit pelanggan |
| Geography | categorical | Negara/Daerah pelanggan |
| Gender | categorical | Jenis kelamin pelanggan |
| Age | int | Usia pelanggan |
| Tenure | int | Lama menjadi nasabah (tahun) |
| Balance | float | Saldo rekening nasabah |
| NumOfProducts | int | Jumlah produk yang dimiliki |
| HasCrCard | int | Memiliki kartu kredit (0/1) |
| IsActiveMember | int | Status keaktifan nasabah (0/1) |
| EstimatedSalary | float | Perkiraan penghasilan tahunan |
| Extited | categorical | Target prediksi: 1 = churn, 0 = tetap |

# **2. Import Library**

Pada tahap ini, perlu mengimpor beberapa pustaka (library) Python yang dibutuhkan untuk analisis data dan pembangunan model machine learning atau deep learning.
"""

# Manipulasi data
import pandas as pd
import numpy as np

# Visualisasi
import matplotlib.pyplot as plt
import seaborn as sns

# Preprocessing
from sklearn.preprocessing import StandardScaler, LabelEncoder

# Clustering
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score

# Mengabaikan warning yang tidak terlalu penting
import warnings
warnings.filterwarnings('ignore')

"""# **3. Memuat Dataset**

Pada tahap ini, memuat dataset ke dalam notebook. Jika dataset dalam format CSV, Anda bisa menggunakan pustaka pandas untuk membacanya. Pastikan untuk mengecek beberapa baris awal dataset untuk memahami strukturnya dan memastikan data telah dimuat dengan benar.

Jika dataset berada di Google Drive, pastikan menghubungkan Google Drive ke Colab terlebih dahulu. Setelah dataset berhasil dimuat, langkah berikutnya adalah memeriksa kesesuaian data dan siap untuk dianalisis lebih lanjut.

Jika dataset berupa unstructured data, silakan sesuaikan dengan format seperti kelas Machine Learning Pengembangan atau Machine Learning Terapan
"""

# Menghubungkan Kaggle API
from google.colab import files
files.upload()  # upload kaggle.json

!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

!kaggle datasets download -d barelydedicated/bank-customer-churn-modeling

# Ekstrak zip dataset
import zipfile

with zipfile.ZipFile("bank-customer-churn-modeling.zip", "r") as zip_ref:
    zip_ref.extractall("bank_data")

# Membaca file CSV dataset
# Nama file bisa 'Bank Customer Churn Dataset.csv' atau sesuai file setelah ekstraksi — sesuaikan jika berbeda
df = pd.read_csv("bank_data/Churn_Modelling.csv")

# Menampilkan 5 baris pertama
df.head()

# Informasi dasar dataset
print("Shape dataset:", df.shape)
print("\nTipe data setiap kolom:")
print(df.dtypes)
print("\nStatistik deskriptif (numerik):")
print(df.describe(include='all'))
print("\nMissing values tiap kolom:")
print(df.isnull().sum())

"""# **4. Exploratory Data Analysis (EDA)**

Pada tahap ini, melakukan **Exploratory Data Analysis (EDA)** untuk memahami karakteristik dataset.

Tujuan dari EDA adalah untuk memperoleh wawasan awal yang mendalam mengenai data dan menentukan langkah selanjutnya dalam analisis atau pemodelan.
"""

# Melihat bentuk dataset
print("Shape Dataset")
df.shape

# Melihat tipe data
print("Tipe Data")
df.dtypes

# Statistik deskriptif
print("Statistik Deskriptif")
print(df.describe(include='all'))

# Mengecek missing values
print("Missing Values")
print(df.isnull().sum())

# Pilih kolom kategorikal
categorical_cols = df.select_dtypes(include=['object']).columns
print("Nilai unik fitur kategorikal")
for col in categorical_cols:
    print(f"{col}: {df[col].nunique()} nilai unik → {df[col].unique()[:10]}")

import matplotlib.pyplot as plt
import seaborn as sns

numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

df[numeric_cols].hist(bins=20, figsize=(15,10))
plt.suptitle("Distribusi Fitur Numerik")
plt.show()

# Exclude kolom ID/unik jika ada
plot_categorical_cols = [col for col in categorical_cols if col not in ['RowNumber','CustomerId','Surname']]

# Tentukan grid subplot
num_plots = len(plot_categorical_cols)
num_cols = 3
num_rows = (num_plots + num_cols - 1) // num_cols

plt.figure(figsize=(num_cols*5, num_rows*4))
for i, col in enumerate(plot_categorical_cols, 1):
    plt.subplot(num_rows, num_cols, i)
    sns.countplot(data=df, x=col)
    plt.xticks(rotation=45, ha='right')
    plt.title(f"Countplot: {col}")
plt.tight_layout()
plt.show()

plt.figure(figsize=(10,8))
sns.heatmap(df[numeric_cols].corr(), annot=True, cmap="coolwarm")
plt.title("Heatmap Korelasi Fitur Numerik")
plt.show()

"""# **5. Data Preprocessing**"""

# Cek lagi missing values
print("Missing values sebelum preprocessing:")
print(df.isnull().sum())

# Menghapus data duplikat
df = df.drop_duplicates()

df = df.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

# Cari kolom kategorikal
categorical_cols = df.select_dtypes(include=['object']).columns

# Label encoding hanya untuk kolom kategori aktif
le = LabelEncoder()
for col in categorical_cols:
    df[col] = le.fit_transform(df[col])

print("[INFO] Kolom yang diencode:", list(categorical_cols))

# Pilih kolom numerik
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns

# Kecualikan kolom
exclude = ['CustomerId', 'RowNumber', 'Exited']
numeric_cols = [col for col in numeric_cols if col not in exclude]

# Scaling
scaler = StandardScaler()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# Contoh visualisasi boxplot untuk outlier
plt.figure(figsize=(12,6))
sns.boxplot(data=df[numeric_cols])
plt.title("Boxplot Fitur Numerik (Outlier Check)")
plt.xticks(rotation=45)
plt.show()

print("Shape dataset setelah preprocessing:", df.shape)
df.head()